apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catalyzator-mongodb
spec:
  serviceName: catalyzator-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: catalyzator-mongodb
  template:
    metadata:
      labels:
        app: catalyzator-mongodb
    spec:
      containers:
      - name: k8s-catalyzator-mongo-db
        image: dichtung/k8s-catalyzator-mongo-db:1.0.0
        # args: ["--bind_ip_all", "--replSet", "rs0"] 
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: k8s-mongo-db-pv-storage
          mountPath: /data/db
  volumeClaimTemplates: # ovde se desava isto sto i u persistentvolumeclaim.yaml fajlu
  - metadata:
      name: k8s-mongo-db-pv-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
    