apiVersion: v1
kind: Service
metadata:
  name: catalyzator-api-svc
spec:
  type: ClusterIP
  selector:
    app: catalyzator-api-pods
  ports:
    - protocol: TCP
      port: 5900
      targetPort: 5900