apiVersion: v1
kind: Service
metadata:
  name: app-nginx-service
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: app-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx-deployment
spec:
  selector:
    matchLabels:
      app: app-nginx
    replicas: 3
    template:
      metadata:
        labels:
          app: app-nginx
          dude: 'true'
      spec:
        containers:
        - name: nginx
          image: nginx:1.17.3
          ports:
          - containerPort: 80