apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
spec:
  serviceName: nginx-sts-svc
  replicas: 3
  selector:
    matchLabels:
      app: nginx-sts-pods
  template:
    metadata:
      labels:
        app: nginx-sts-pods
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80